72885 improve configuration of whether reference detail pages should be shown
onOffice-Web-Org/oo-wp-plugin pull request #276
Opened 2022-06-20 03:24 UTC by dai-eastgate

2022-06-27 09:25 UTC, LongTrong-exe submitted a review, later dismissed

2022-06-30 02:46 UTC, LongTrong-exe approved these changes

2022-07-04 15:00 UTC, jmaas-onoffice requested changes
Minor nitpick: In the description "... because the access is [restricted](https://testinstanz-jmaa.onofficeweb.com/wp-admin/admin.php?page=onoffice-estates&tab=detail)", there is a period missing at the end. (It should be "... because the access is [restricted](https://testinstanz-jmaa.onofficeweb.com/wp-admin/admin.php?page=onoffice-estates&tab=detail).")

Other than that a quick test of the functionality looks good already! :)

2022-07-05 01:57 UTC, dai-eastgate commented on plugin/Installer/DatabaseChanges.php
>  			$dbversion = 32;
yes, it is. I implement this to migrate the old data.

2022-07-05 06:55 UTC, jmaas-onoffice commented on plugin/Installer/DatabaseChanges.php
>  			$dbversion = 32;
But should this be done when `$dbVersion == 31` or should it get a new version?

2022-07-05 07:46 UTC, dai-eastgate commented on plugin/Installer/DatabaseChanges.php
>  			$dbversion = 32;
I think `$dbVersion == 31` is the current version (that we are developing). Please correct it if I'm wrong. Is the code for `$this->_pWpOption->addOption('onoffice-is-encryptcredent', false);` already release?

2022-07-05 08:14 UTC, jmaas-onoffice commented on plugin/Installer/DatabaseChanges.php
>  			$dbversion = 32;
If `$dbVersion == 31` is in master, do we need a new version? Could you check this?

2022-07-05 09:30 UTC, dai-eastgate commented on plugin/Installer/DatabaseChanges.php
>  			$dbversion = 32;
I just checked it. We need a new version. I updated the code. Please check it.

2022-07-05 09:50 UTC, jmaas-onoffice commented on plugin/Installer/DatabaseChanges.php
>  			$dbversion = 32;
Thanks! I'm not an expert on how the code works, so I'm relying on you... :D But I will test it. 👍

2022-07-13 10:29 UTC, jmaas-onoffice approved these changes

2022-07-13 10:47 UTC, jmaas-onoffice commented
This works great, thanks! I'll just wait and see if we can make the tests pass, by restarting them later.

2022-07-14 06:50 UTC, jmaas-onoffice approved these changes

2022-07-14 07:33 UTC, jmaas-onoffice requested changes
Unfortunately, I forgot to test a few cases and I found a migration problem:

If on v4.2 in the detail view I have set the reference estates to be accessible:

![grafik](https://user-images.githubusercontent.com/90763364/178921955-8beaa082-0067-48df-b468-d98ad7349391.png)

And then I upgrade, suddenly the reference pages are restricted:

![grafik](https://user-images.githubusercontent.com/90763364/178922506-5bb1ba91-c199-4126-b2ef-c080b59db078.png)

This also happens if on v4.2 the reference detail pages are not accessible. That means that with the update, the reference pages are always set to be restricted.

But for existing installations, the reference estates detail page should keep the accessibility from before the update. Only for new installations should the default be that they are restricted.

2022-07-26 09:43 UTC, jmaas-onoffice approved these changes

2022-07-26 10:01 UTC, jmaas-onoffice commented
When the problem with the unit tests is solved, we can merge this.

2022-07-27 10:35 UTC, merged