P#77244 Template groups are not translated
onOffice-Web-Org/oo-wp-plugin pull request #315
Opened 2022-08-23 02:50 UTC by dai-eastgate

2022-09-08 02:36 UTC, LongTrong-exe approved these changes

2022-09-08 03:16 UTC, LongTrong-exe approved these changes

2022-09-08 07:14 UTC, jmaas-onoffice requested changes
Since we merged #288, the language files (.mo and .po) should not be updated anymore.

2022-09-12 10:16 UTC, jmaas-onoffice approved these changes

2022-09-12 10:19 UTC, merged