31367 GDPR (checkbox) Field not recognised
onOffice-Web-Org/oo-wp-plugin pull request #460
Opened 2023-03-09 03:58 UTC by dai-eastgate

2023-03-21 09:41 UTC, andernath requested changes
@dai-eastgate Could you please take a look inside codereview?

2023-03-21 09:41 UTC, andernath commented on plugin/Renderer/InputFieldButtonAddRemoveRenderer.php
> +	public function getModule(string $key, FieldsCollection $pFieldsCollection): string
Is public visibility necessary?

2023-03-21 09:41 UTC, andernath commented on plugin/Renderer/InputFieldButtonAddRemoveRenderer.php
> +	public function buildFieldsCollection(): FieldsCollection
Is public visibility necessary?

2023-03-22 03:41 UTC, dai-eastgate commented
@andernath Please check this PR also :)

2023-03-22 07:09 UTC, andernath approved these changes
Thank you :)

2023-03-22 07:35 UTC, merged