51535 Persistence of the property list with missing or same name
onOffice-Web-Org/oo-wp-plugin pull request #876
Opened 2024-08-07 11:02 UTC by dai-eastgate

related to https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/865
changed log:
Update feature notification for missing or same name and unsaved changes

2025-04-24 07:46 UTC, n-nelles-onOffice submitted a review, later dismissed
dont merge yet, I just want to trigger the build

2025-05-02 08:45 UTC, Vogl01 requested changes
Nur ein paar Spitzfindigkeiten, du darfst selbst entscheiden ob du das mit hereinnimmst oder nicht.

2025-05-02 08:45 UTC, Vogl01 commented on plugin/Record/RecordManagerReadForm.php
> +
Da diese Methode in allen RecordManagerRead* vorkommt, denke ich, dass es Sinn ergibt die Deklaration der Methode in die Parent-Class zu packen. Dann würden wir sicherstellen dass alle künftigen RecordManagerRead auch diese Methode implementieren.
```+ public function checkSameName(string $name, string $id = null): bool;```
in RecordManagerRead.php

2025-05-02 08:45 UTC, Vogl01 commented on plugin/Record/RecordManagerReadForm.php
> +		$sql = "SELECT COUNT(*) AS count
```suggestion
		$sql = "SELECT COUNT(*) AS count
```

2025-05-05 13:00 UTC, n-nelles-onOffice commented on plugin/Record/RecordManagerReadForm.php
> +
625d56263128bc906e137beb06e842971765c139

2025-05-07 06:31 UTC, Vogl01 approved these changes

2025-05-07 06:37 UTC, merged